spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hobbes_the_project
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: hobbes
    password: hobbes
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 431E9259EE162EDCB569578527E22
      expiration: 900000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account